### ISSUE TITLE
WARNING:kolibri_gnome.globals:Error loading translation file: [Errno 2] No translation file found for domain: 'kolibri-gnome'

### ISSUE THREAD

**Issue by LeandroStanger** [learningequality/kolibri-installer-gnome#2]
```
WARNING:kolibri_gnome.globals:Error loading translation file: [Errno 2] No translation file found for domain: 'kolibri-gnome'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/main.py", line 43, in <module>
    result = main()
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/main.py", line 35, in main
    app = Application()
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/application.py", line 242, in __init__
    os.path.join(config.DATA_DIR, "assets", "_load.html"),
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/utils.py", line 14, in get_localized_file
    language_base = language.split("_", 1)[0]
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by wjt** [comment]
@LeandroStanger please provide the output of `flatpak list --app --show-details` and `flatpak list --runtime --show-details` (such as by running `eos-diagnostics`)

**Comment by wjt** [comment]
```
wjt@camille:~$ LANG=xx_XX.utf8 org.learningequality.Kolibri 


(main.py:4): Gtk-WARNING **: 21:10:38.303: Locale not supported by C library.
	Using the fallback 'C' locale.
WARNING:kolibri_gnome.globals:Error loading translation file: [Errno 2] No translation file found for domain: 'kolibri-gnome'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/main.py", line 43, in <module>
    result = main()
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/main.py", line 35, in main
    app = Application()
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/application.py", line 242, in __init__
    os.path.join(config.DATA_DIR, "assets", "_load.html"),
  File "/app/lib/python3.7/site-packages/kolibri_gnome/desktop_launcher/utils.py", line 14, in get_localized_file
    language_base = language.split("_", 1)[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

I think the issue is that your locale is `pt_BR` and there are no Portuguese translations.

**Comment by dylanmccall** [comment]
Thanks @LeandroStanger ! I'm pushing a fix for that now :)
